### ISSUE TITLE
Added Programs for Linked Lists

### ISSUE THREAD

**Issue by divyansh-ag-03** [Sanchitbajaj02/Hacktoberfest-2022#6]
I have added 2 programs for the implementation of Linked Lists.
Please consider them.

**Comment by AvinashChourasia** [comment]
Hi @Sanchitbajaj02, can you assign this task to me.
I want to add some good problems of linked list.

**Comment by Sanchitbajaj02** [comment]
Not accepting any more PR as it seems the repository is excluded
